export const BAR = "BAR/BAR";

export const BAR_ADD_FIELD_ROW = `${BAR}_ADD_FIELD_ROW`;
export const BAR_REMOVE_FIELD_ROW = `${BAR}_REMOVE_FIELD_ROW`;
export const BAR_UPDATE_FIELD_ROW = `${BAR}_UPDATE_FIELD_ROW`;

export const BAR_ADD_DROPZONE_FILE = `${BAR}_ADD_DROPZONE_FILE`;
export const BAR_REMOVE_DROPZONE_FILE = `${BAR}_REMOVE_DROPZONE_FILE`;

export const BAR_ADD_IPFS_FILE = `${BAR}_ADD_IPFS_FILE`;

export const BAR_SET_ASSET_REFERENCE = `${BAR}_SET_ASSET_REFERENCE`;
export const BAR_SET_ASSET_VERSIONS = `${BAR}_SET_ASSET_VERSIONS`;

export const BAR_TOGGLE_OUTPUT_VIEW = `${BAR}_TOGGLE_OUTPUT_VIEW`;
export const BAR_TOGGLE_PUBLISH_VIEW = `${BAR}_TOGGLE_PUBLISH_VIEW`;

export const NAMESPACE = "BARReducer";
